using AdventOfCode2022;
Console.WriteLine("AOC 2022!");
Console.WriteLine("Day 11:"); _11.Run();

Console.WriteLine("Day 1:"); _1.Run();
Console.WriteLine("Day 2:"); _2.Run();
Console.WriteLine("Day 3:"); _3.Run();
Console.WriteLine("Day 4:"); _4.Run();
Console.WriteLine("Day 5:"); _5.Run();
Console.WriteLine("Day 6:"); _6.Run();
Console.WriteLine("Day 7:"); _7.Run();
Console.WriteLine("Day 8:"); _8.Run();
Console.WriteLine("Day 9:"); _9.Run();
Console.WriteLine("Day 10:"); _10.Run();
Console.WriteLine("Day 11:"); _11.Run();
Console.WriteLine("Day 12:"); _12.Run();
Console.WriteLine("Day 13:"); _13.Run();
Console.WriteLine("Day 14:"); _14.Run();
Console.WriteLine("Day 15:"); _15.Run();
Console.WriteLine("Day 16:"); _16.Run();
Console.WriteLine("Day 17:"); _17.Run();
Console.WriteLine("Day 18:"); _18.Run();
Console.WriteLine("Day 19:"); _19.Run();
Console.WriteLine("Day 20:"); _20.Run();
Console.WriteLine("Day 21:"); _21.Run();
Console.WriteLine("Day 22:"); _22.Run();
Console.WriteLine("Day 23:"); _23.Run();
Console.WriteLine("Day 24:"); _24.Run();
Console.WriteLine("Day 25:"); _25.Run();
